import '../../l10n/app_l10n.dart';

/// Localized via [appL10n] — keys in `lib/l10n/app_en.arb`.
abstract final class BookingStrings {
  static String get title => appL10n.bookingTitle;
  static String get pastBookingTitle => appL10n.bookingPastBookingTitle;
  static String get today => appL10n.bookingToday;
  static String get noBookingListed => appL10n.bookingNoBookingListed;
  static String get filter => appL10n.bookingFilter;
  static String get bookingStatus => appL10n.bookingBookingStatus;
  static String get lastUpdatedToday => appL10n.bookingLastUpdatedToday;
  static String get pastBookingChip => appL10n.bookingPastBookingChip;
  static String get submittedOn => appL10n.bookingSubmittedOn;
  static String get chooseDate => appL10n.bookingChooseDate;
  static String get bookingType => appL10n.bookingBookingType;
  static String get clear => appL10n.bookingClear;
  static String get apply => appL10n.bookingApply;
  static String get searchTitle => appL10n.bookingSearchTitle;
  static String get searchHint => appL10n.bookingSearchHint;
  static String get searchMinChars => appL10n.bookingSearchMinChars;
  static String get searchAction => appL10n.bookingSearchAction;
  static String get cancel => appL10n.bookingCancel;
  static String get filterPickOne => appL10n.bookingFilterPickOne;
  static String get tabAllBookings => appL10n.bookingTabAllBookings;
  static String get tabCheckedIn => appL10n.bookingTabCheckedIn;
  static String get tabUpcoming => appL10n.bookingTabUpcoming;
  static String get emptyAllBookings => appL10n.bookingEmptyAllBookings;
  static String get emptyCheckedIn => appL10n.bookingEmptyCheckedIn;
  static String get emptyUpcoming => appL10n.bookingEmptyUpcoming;
  static String get loadFailed => appL10n.bookingLoadFailed;
  static String get detailsTitle => appL10n.bookingDetailsTitle;
  static String get checkIn => appL10n.bookingCheckIn;
  static String get checkOut => appL10n.bookingCheckOut;
  static String get confirmCheckIn => appL10n.bookingConfirmCheckIn;
  static String get confirmCheckOut => appL10n.bookingConfirmCheckOut;
  static String get yes => appL10n.bookingYes;
  static String get no => appL10n.bookingNo;
  static String get updated => appL10n.bookingUpdated;
  static String get checkInSuccess => appL10n.bookingCheckInSuccess;
  static String get checkOutSuccess => appL10n.bookingCheckOutSuccess;
  static String get category => appL10n.bookingCategory;
  static String get room => appL10n.bookingRoom;
  static String get unit => appL10n.bookingUnit;
  static String get guest => appL10n.bookingGuest;
  static String get mobile => appL10n.bookingMobile;
  static String get authName => appL10n.bookingAuthName;
  static String get authContact => appL10n.bookingAuthContact;
  static String get authIc => appL10n.bookingAuthIc;
  static String get duration => appL10n.bookingDuration;
  static String get startTime => appL10n.bookingStartTime;
  static String get endTime => appL10n.bookingEndTime;
  static String get submitted => appL10n.bookingSubmitted;
  static String get arrival => appL10n.bookingArrival;
  static String get exit => appL10n.bookingExit;
  static String get attendees => appL10n.bookingAttendees;
  static String get callGuest => appL10n.bookingCallGuest;
}
